### ISSUE TITLE
is there any news for big sure

### ISSUE THREAD

**Issue by hatemragab** [Nosskirneh/Hackintosh-HP-Z440-macOS-High-Sierra-10.13#4]
is there any news for big sure thanks bro

**Comment by Nosskirneh** [comment]
Any news for what?

**Comment by hatemragab** [comment]
Efi for big sur

**Comment by Nosskirneh** [comment]
I have a NVIDIA card so I’m still at High Sierra. Feel free to contribute.

**Comment by hatemragab** [comment]
I have amd rx 580 and catilna working good problems come when try upgrade 😥 can you help me

**Comment by Nosskirneh** [comment]
I’d recommend you to ask for guidance in r/Hackintosh or at their Discord.

**Comment by hatemragab** [comment]
Are u have discord link?

**Comment by Nosskirneh** [comment]
https://discord.gg/u8V7N5C
